### ISSUE TITLE
Playing on Diluvian reduces chest spawn rates noticeably

### ISSUE THREAD

**Issue by blazingdrummer** [blazingdrummer/BakedModpack#1]
Originally reported by CarlosPCMR w/ a 3 man squad.

This shouldn't be the case, since I don't believe Diluvian affects interactable credits at all.
"2 chests stage 1", "3 chests stage 2"
I think this might just be a case of ShareSuite's experimental scaling in action, but those numbers seem a bit too harsh.

Note that this is using ShareSuite v1.15.1. Will be updating shortly.

@Sipondo @FunkFrog is ShareSuite still scaling back chests for the first few levels to compensate for early item spike? Or have you instead increased enemy difficulty (I'm assuming by increasing director credits) as stated [here](https://github.com/FunkFrog/RoR2SharedItems/issues/76#issuecomment-574033263).

**Comment by Sipondo** [comment]
no it completely overwrites the game init of director credits

**Comment by blazingdrummer** [comment]
Hmm ok. Is that a formula based off of the original credit count, or completely custom? Essentially asking if other mods that affect director credits would be taking into account.

**Comment by Sipondo** [comment]
It's based on the original formula but it overwrites.

**Comment by blazingdrummer** [comment]
Ok I just got another report of similar behavior on Easy and Medium difficulty. Going to focus on updating the pack to ShareSuite v2.0.0 before investigating the issue further.

**Comment by Sipondo** [comment]
Yeah let us know!

**Comment by blazingdrummer** [comment]
OK, I've played multiplayer myself at this point. I can confirm that chest rates are pretty low, but feel balanced imo and no different than they always have been. For those of you experiencing this, please remember that even if only 3 chests spawn for a group of 3, they are still getting a total of 9 items across the group, which is comparable to vanilla multiplayer. While singleplayer might yield more items on an early floor, they aren't equivalent in power to 3 characters all using items and abilities simultaneously.

The only doubts I have remaining on the issue are how will this system will scale with very large groups (10+). It does have the possibility of breaking down, but I personally haven't seen this become an issue yet, and am holding out hope that it will scale well even into large groups (which may experience a whole new set of problems anyways).

**Comment by Sipondo** [comment]
We have custom code in place that handles this scaling in a balanced way and that prevents breaking down on abnormally large party sizes, so it should not be an issue.
Glad to hear it works on Diluvian.
