### ISSUE TITLE
Scavengers can currently get Adaptive Filament

### ISSUE THREAD

**Issue by blazingdrummer** [blazingdrummer/BakedModpack#4]
Caused by AI Blacklister removing the item from the blacklist because I can't reference it in the list. Unsure of how this interaction will work. Will the Scavenger get duplicates of its next green-or-lower pull from the bag? Would that trigger Adaptive? If it does, I might consider letting them have it, because it's interesting. If it's useless, it should probably be blacklisted. Might be able to test by playing as Scavenger. Either way, I'm working with Sciman101 on the issue.

**Comment by urbanawakening** [comment]
This is caused by an upstream R2API issue. I'd assume that it'd get one duplicate of whatever it picks up first. I.E Scavenger picks up Syringe[5], the item turns into Syringe[1]. However, since the source code is not available, it is only an assumption for now.

**Comment by blazingdrummer** [comment]
I haven't actually checked the behavior with Scavengers, but I do know the root cause with PocketPrinter's interaction with AI Blacklister. If the interaction doesn't work as intended, then I'll blacklist it once that is working. Thanks for the info.

**Comment by harbingerofme** [comment]
AI Blacklister should be working fine if you use the internal name for the item: `PocketPrinter`

**Comment by blazingdrummer** [comment]
I thought I tried that... I'll try it again. Thanks.

**Comment by blazingdrummer** [comment]
Worked perfectly. My mistake, I have no idea how that slipped by. I'll let Sciman101 know.
